version: '3.8'

services:
  backend1:
    build:
      context: .
      dockerfile: backend1.Dockerfile
    ports:
      - "5000:5000"

  backend2:
    build:
      context: .
      dockerfile: backend2.Dockerfile
    ports:
      - "5001:5001"

  load_balancer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2